# Codecov Configuration
# https://docs.codecov.io/docs/codecovyml-reference

coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project:
      default:
        target: 70%
        threshold: 5%
        informational: true
    patch:
      default:
        target: 60%
        threshold: 5%

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach,diff,flags,files"
  behavior: default
  require_changes: false

ignore:
  - "backend/tests/**/*"
  - "backend/src/utils/seed.js"
  - "backend/migrations/**/*"
